listen              1935;
max_connections     1000;
daemon              off;
srs_log_tank        console;

http_server {
    enabled         on;
    listen          8080;
    dir             ./objs/nginx/html;
}

http_api {
    enabled         on;
    listen          1985;
}

vhost __defaultVhost__ {
    min_latency     on;
    tcp_nodelay     on;

    play {
        gop_cache   on;
        queue_length 10;
    }

    publish {
        mr          off;
    }

    application live {
        live        on;
        gop_cache   on;

        hls         off;
        hds         off;
        dash        off;

        rtc {
            enabled off;
        }
    }
}
